// Canvas & Display Configuration
export const CANVAS_CONFIG = {
  WIDTH: 1200,
  HEIGHT: 900,
  CROSSHAIR_SIZE: 10,
  MOUSE_OFFSET: 50
};

// World Configuration
export const WORLD_CONFIG = {
  WIDTH: 6000,
  HEIGHT: 5500,
  VIEWPORT_WIDTH: 1200, // CANVAS_WIDTH
  VIEWPORT_HEIGHT: 900  // CANVAS_HEIGHT
};

// Ship Configuration
export const SHIP_CONFIG = {
  SIZE: 10,
  SPEED: 0.12,
  FRICTION: 0.99,
  DECELERATION: 0.92,
  INITIAL_LIVES: 3
};

// Weapon Configuration
const FIRE_RATE_MS = 250; // 4 shots per second
export const WEAPON_CONFIG = {
  BULLET_FIRE_RATE: FIRE_RATE_MS,
  BULLET_SPEED: 20,
  BULLET_LIFETIME: 100, // frames
  BULLET_SIZE: 2,
  BULLET_RANGE: 1200 * 2, // twice viewport width
  MAX_BULLETS: 5
};

// Asteroid Configuration
export const ASTEROID_CONFIG = {
  SPEED: 2,
  SIZE_LARGE: 40,
  SIZE_MEDIUM: 20,
  SIZE_SMALL: 10,
  SPLIT_SPEED_VARIANCE: 0.4,
  ROTATION_VARIANCE: 0.1,
  POINT_RANGE: 4,
  INITIAL_COUNT: 5
};

// Scoring & Progression
export const SCORING_CONFIG = {
  SCORE_PER_ASTEROID: 10,
  XP_PER_ASTEROID: 18,
  XP_LEVEL_BASE: 300,
  XP_LEVEL_GROWTH: 1.25
};

// Star Configuration
export const STAR_CONFIG = {
  COUNT: 2000,
  MIN_BRIGHTNESS: 0.2,
  MAX_BRIGHTNESS: 1.0,
  LARGE_THRESHOLD: 0.7,
  MEDIUM_THRESHOLD: 0.4,
  FIELD_MULTIPLIER: 3,
  FIELD_SPREAD: 1.5,
  MIN_PARALLAX: 0.3,
  MAX_PARALLAX: 0.7
};

// Camera Configuration
export const CAMERA_CONFIG = {
  MAX_ZOOM_OUT: 3,
  MIN_ZOOM: 1,
  ZOOM_SPEED: 0.1,
  ZOOM_INTERPOLATION: 0.1
};

// Effect Configurations
export const LEVELUP_CONFIG = {
  PARTICLES: 225,
  PARTICLE_SPEED: 12,
  PARTICLE_LIFE: 40,
  FLASH_DECAY: 0.06,
  TEXT_TIME: 75
};

export const STAGE_CLEAR_CONFIG = {
  SLIDE_TIME: 30,
  POP_TIME: 15,
  HOLD_TIME: 45,
  FADE_TIME: 20
};

export const HYPERSPACE_CONFIG = {
  STREAK_TIME: 60,
  FADE_TIME: 30,
  TEXT_TIME: 30,
  BRIGHTEN_TIME: 20,
  FLASH_TIME: 8
};

// Legacy exports for backward compatibility
export const CANVAS_WIDTH = CANVAS_CONFIG.WIDTH;
export const CANVAS_HEIGHT = CANVAS_CONFIG.HEIGHT;
export const SHIP_SIZE = SHIP_CONFIG.SIZE;
export const SHIP_SPEED = SHIP_CONFIG.SPEED;
export const BULLET_FIRE_RATE = WEAPON_CONFIG.BULLET_FIRE_RATE;
export const BULLET_SPEED = WEAPON_CONFIG.BULLET_SPEED;
export const BULLET_LIFETIME = WEAPON_CONFIG.BULLET_LIFETIME;
export const BULLET_SIZE = WEAPON_CONFIG.BULLET_SIZE;
export const BULLET_RANGE = WEAPON_CONFIG.BULLET_RANGE;
export const ASTEROID_SPEED = ASTEROID_CONFIG.SPEED;
export const ASTEROID_SIZE_LARGE = ASTEROID_CONFIG.SIZE_LARGE;
export const ASTEROID_SIZE_MEDIUM = ASTEROID_CONFIG.SIZE_MEDIUM;
export const ASTEROID_SIZE_SMALL = ASTEROID_CONFIG.SIZE_SMALL;
export const ASTEROID_SPLIT_SPEED_VARIANCE = ASTEROID_CONFIG.SPLIT_SPEED_VARIANCE;
export const ASTEROID_ROTATION_VARIANCE = ASTEROID_CONFIG.ROTATION_VARIANCE;
export const ASTEROID_POINT_RANGE = ASTEROID_CONFIG.POINT_RANGE;
export const STAR_COUNT = STAR_CONFIG.COUNT;
export const STAR_MIN_BRIGHTNESS = STAR_CONFIG.MIN_BRIGHTNESS;
export const STAR_MAX_BRIGHTNESS = STAR_CONFIG.MAX_BRIGHTNESS;
export const INITIAL_ASTEROID_COUNT = ASTEROID_CONFIG.INITIAL_COUNT;
export const MAX_BULLETS = WEAPON_CONFIG.MAX_BULLETS;
export const CROSSHAIR_SIZE = CANVAS_CONFIG.CROSSHAIR_SIZE;
export const MOUSE_OFFSET = CANVAS_CONFIG.MOUSE_OFFSET;
export const SCORE_PER_ASTEROID = SCORING_CONFIG.SCORE_PER_ASTEROID;
export const INITIAL_LIVES = SHIP_CONFIG.INITIAL_LIVES;
export const XP_PER_ASTEROID = SCORING_CONFIG.XP_PER_ASTEROID;
export const XP_LEVEL_BASE = SCORING_CONFIG.XP_LEVEL_BASE;
export const XP_LEVEL_GROWTH = SCORING_CONFIG.XP_LEVEL_GROWTH;
export const LEVELUP_PARTICLES = LEVELUP_CONFIG.PARTICLES;
export const LEVELUP_PARTICLE_SPEED = LEVELUP_CONFIG.PARTICLE_SPEED;
export const LEVELUP_PARTICLE_LIFE = LEVELUP_CONFIG.PARTICLE_LIFE;
export const LEVELUP_FLASH_DECAY = LEVELUP_CONFIG.FLASH_DECAY;
export const LEVELUP_TEXT_TIME = LEVELUP_CONFIG.TEXT_TIME;
export const STAGE_CLEAR_SLIDE_TIME = STAGE_CLEAR_CONFIG.SLIDE_TIME;
export const STAGE_CLEAR_POP_TIME = STAGE_CLEAR_CONFIG.POP_TIME;
export const STAGE_CLEAR_HOLD_TIME = STAGE_CLEAR_CONFIG.HOLD_TIME;
export const STAGE_CLEAR_FADE_TIME = STAGE_CLEAR_CONFIG.FADE_TIME;
export const HYPERSPACE_STREAK_TIME = HYPERSPACE_CONFIG.STREAK_TIME;
export const HYPERSPACE_FADE_TIME = HYPERSPACE_CONFIG.FADE_TIME;
export const HYPERSPACE_TEXT_TIME = HYPERSPACE_CONFIG.TEXT_TIME;
export const HYPERSPACE_BRIGHTEN_TIME = HYPERSPACE_CONFIG.BRIGHTEN_TIME;
export const HYPERSPACE_FLASH_TIME = HYPERSPACE_CONFIG.FLASH_TIME;
export const STAR_LARGE_THRESHOLD = STAR_CONFIG.LARGE_THRESHOLD;
export const STAR_MEDIUM_THRESHOLD = STAR_CONFIG.MEDIUM_THRESHOLD;
export const VIEWPORT_WIDTH = WORLD_CONFIG.VIEWPORT_WIDTH;
export const VIEWPORT_HEIGHT = WORLD_CONFIG.VIEWPORT_HEIGHT;
export const WORLD_WIDTH = WORLD_CONFIG.WIDTH;
export const WORLD_HEIGHT = WORLD_CONFIG.HEIGHT;
export const MAX_ZOOM_OUT = CAMERA_CONFIG.MAX_ZOOM_OUT;
export const MIN_ZOOM = CAMERA_CONFIG.MIN_ZOOM;
export const ZOOM_SPEED = CAMERA_CONFIG.ZOOM_SPEED;
export const SHIP_FRICTION = SHIP_CONFIG.FRICTION;
export const SHIP_DECELERATION = SHIP_CONFIG.DECELERATION;
export const ZOOM_INTERPOLATION = CAMERA_CONFIG.ZOOM_INTERPOLATION;
export const STAR_FIELD_MULTIPLIER = STAR_CONFIG.FIELD_MULTIPLIER;
export const STAR_FIELD_SPREAD = STAR_CONFIG.FIELD_SPREAD;
export const MIN_PARALLAX = STAR_CONFIG.MIN_PARALLAX;
export const MAX_PARALLAX = STAR_CONFIG.MAX_PARALLAX;
